
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/busking_db
    username: root
    password: "@ace963492"
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your_google_id #깃허브 사용 시 가릴 것!
            client-secret: your_google_password #깃허브 사용 시 가릴 것!
            redirect-uri: http://localhost:8080/login/oauth2/code/google #깃허브 사용 시 가릴 것!
            scope: profile, email
          kakao:
            client-id: your_kakao_id #깃허브 사용 시 가릴 것!
            client-secret: ""
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize?prompt=login
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


